name: build-image
on: [push]
jobs:
  build-image-on-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install -y awscli
      - env:
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./run-aws.sh
